openapi: 3.0.1
info:
  title: 계정 API
  description: 광고 계정과 관리 계정 정보를 조회할 수 있습니다.
  version: '1.0'
servers:
  - url: https://openapi.naver.com/v1/ad-api
tags:
  - name: 광고 계정
    description: 광고 계정 목록과 상세 정보를 조회합니다.
  - name: 관리 계정
    description: 관리 계정 목록과 상세 정보를 조회합니다.
paths:
  /{version}/adAccounts:
    get:
      tags:
        - 광고 계정
      summary: 내 광고 계정 목록
      operationId: listUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageOpenAdAccount'
      deprecated: false
      parameters:
        - name: page
          in: query
          description: '페이지 번호 (기본값: 0)'
          schema:
            type: integer
        - name: size
          in: query
          description: '페이지 크기 (기본값: 10, 최대: 100)'
          schema:
            type: integer
        - name: version
          in: path
          description: API 버전
          required: true
          schema:
            type: number
            format: float
            default: 1
  /{version}/adAccounts/{adAccountNo}:
    get:
      tags:
        - 광고 계정
      summary: 광고 계정 조회
      operationId: getUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OpenAdAccount'
      deprecated: false
      parameters:
        - name: AccessManagerAccountNo
          in: header
          description: 해당 광고 계정에 대한 접근 권한이 있는 관리 계정 ID
          required: false
          schema:
            type: integer
            format: int64
        - name: adAccountNo
          in: path
          description: 광고 계정 ID
          required: true
          schema:
            type: integer
            format: int64
        - name: version
          in: path
          description: API 버전
          required: true
          schema:
            type: number
            format: float
            default: 1
  /{version}/managerAccounts:
    get:
      tags:
        - 관리 계정
      summary: 내 관리 계정 목록
      operationId: listUsingGET_1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageOpenMyManagerAccount'
      deprecated: false
      parameters:
        - name: page
          in: query
          description: '페이지 번호 (기본값: 0)'
          schema:
            type: integer
        - name: size
          in: query
          description: '페이지 크기 (기본값: 10, 최대: 100)'
          schema:
            type: integer
        - name: version
          in: path
          description: API 버전
          required: true
          schema:
            type: number
            format: float
            default: 1
  /{version}/managerAccounts/{managerAccountNo}:
    get:
      tags:
        - 관리 계정
      summary: 관리계정 조회
      description: 응답 결과에는 관리 계정 정보와 하위의 모든 depth의 관리 계정/광고 계정NO 정보를 포함하고 있습니다.
      operationId: getUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OpenManagerAccount'
      deprecated: false
      parameters:
        - name: AccessManagerAccountNo
          in: header
          description: 해당 관리 계정에 대한 접근 권한이 있는 관리 계정 ID
          required: true
          schema:
            type: integer
            format: int64
        - name: managerAccountNo
          in: path
          description: 관리 계정 ID
          required: true
          schema:
            type: integer
            format: int64
        - name: version
          in: path
          description: API 버전
          required: true
          schema:
            type: number
            format: float
            default: 1
components:
  schemas:
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
    OpenAdAccount:
      type: object
      properties:
        'no':
          type: integer
          description: 광고 계정 ID
          format: int64
        name:
          type: string
          description: 광고 계정 이름
        disabled:
          type: boolean
          description: 비활성화 여부
        role:
          type: string
          description: 권한 레벨 정보
          enum:
            - OWNER
            - MASTER
            - STANDARD
            - READ_ONLY
            - PERFORMANCE_MANAGEMENT
        createdAt:
          type: string
          description: 생성 일시
          format: date-time
        updatedAt:
          type: string
          description: 최종 수정 일시
          format: date-time
      description: OpenAPI 광고 계정 응답
    PageOpenAdAccount:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        pageable:
          $ref: '#/components/schemas/PageableObject'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/SortObject'
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/OpenAdAccount'
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/SortObject'
        paged:
          type: boolean
        unpaged:
          type: boolean
        offset:
          type: integer
          format: int64
    SortObject:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean
    OpenMyManagerAccount:
      type: object
      properties:
        'no':
          type: integer
          format: int64
          description: 관리 계정 ID
        name:
          type: string
          description: 관리 계정 이름
        disabled:
          type: boolean
          description: 비활성화 여부
        createdAt:
          type: string
          format: date-time
          description: 생성 일시
        updatedAt:
          type: string
          format: date-time
          description: 최종 수정 일시
        role:
          type: string
          description: 권한 레벨 정보
          enum:
            - OWNER
            - MASTER
            - STANDARD
            - READ_ONLY
            - PERFORMANCE_MANAGEMENT
    PageOpenMyManagerAccount:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        pageable:
          $ref: '#/components/schemas/PageableObject'
        first:
          type: boolean
        last:
          type: boolean
        sort:
          $ref: '#/components/schemas/SortObject'
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/OpenMyManagerAccount'
        empty:
          type: boolean
    OpenManagerAccount:
      type: object
      properties:
        childAdAccountNos:
          type: array
          description: 하위의 광고 계정 ID
          items:
            type: integer
            format: int64
            description: 하위의 광고 계정 ID
        childManagerAccounts:
          type: array
          description: 하위의 관리 계정
          items:
            $ref: '#/components/schemas/OpenManagerAccount'
        createdAt:
          type: string
          format: date-time
          description: 생성 일시
        disabled:
          type: boolean
          description: 비활성화 여부
        name:
          type: string
          description: 관리 계정 이름
        'no':
          type: integer
          format: int64
          description: 관리 계정 ID
        updatedAt:
          type: string
          format: date-time
          description: 최종 수정 일시
      title: OpenManagerAccount
