openapi: 3.0.1
info:
  title: Account API
  description: Retrieve ad account and manager account information.
  version: '1.0'
servers:
  - url: https://openapi.naver.com/v1/ad-api
tags:
  - name: Ad accounts
    description: Retrieves the ad account list and detailed information.
  - name: Manager accounts
    description: Retrieves the manager account list and detailed information.
paths:
  /{version}/adAccounts:
    get:
      tags:
        - Ad accounts
      summary: List of my ad accounts
      operationId: listUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageOpenAdAccount'
      deprecated: false
      parameters:
        - name: page
          in: query
          description: 'Page number (default: 0)'
          schema:
            type: integer
        - name: size
          in: query
          description: 'Page size (default: 10, max: 100)'
          schema:
            type: integer
        - name: version
          in: path
          description: API version
          required: true
          schema:
            type: number
            format: float
            default: 1
  /{version}/adAccounts/{adAccountNo}:
    get:
      tags:
        - Ad accounts
      summary: Get an ad account
      operationId: getUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OpenAdAccount'
      deprecated: false
      parameters:
        - name: AccessManagerAccountNo
          in: header
          description: Manager account ID that has access to the ad account
          required: false
          schema:
            type: integer
            format: int64
        - name: adAccountNo
          in: path
          description: ad account ID
          required: true
          schema:
            type: integer
            format: int64
        - name: version
          in: path
          description: API version
          required: true
          schema:
            type: number
            format: float
            default: 1
  /{version}/managerAccounts:
    get:
      tags:
        - Manager accounts
      summary: List of my manager accounts
      operationId: listUsingGET_1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageOpenMyManagerAccount'
      deprecated: false
      parameters:
        - name: page
          in: query
          description: 'Page number (default: 0)'
          schema:
            type: integer
        - name: size
          in: query
          description: 'Page size (default: 10, max: 100)'
          schema:
            type: integer
        - name: version
          in: path
          description: API version
          required: true
          schema:
            type: number
            format: float
            default: 1
  /{version}/managerAccounts/{managerAccountNo}:
    get:
      tags:
        - Manager accounts
      summary: Get a manager account
      description: >-
        Returns manager account information including its child manager accounts
        and ad account numbers.
      operationId: getUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OpenManagerAccount'
      deprecated: false
      parameters:
        - name: AccessManagerAccountNo
          in: header
          description: Manager account ID that has access to the manager account
          required: true
          schema:
            type: integer
            format: int64
        - name: managerAccountNo
          in: path
          description: manager account ID
          required: true
          schema:
            type: integer
            format: int64
        - name: version
          in: path
          description: API version
          required: true
          schema:
            type: number
            format: float
            default: 1
components:
  schemas:
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
    OpenAdAccount:
      type: object
      properties:
        'no':
          type: integer
          description: Ad account ID
          format: int64
        name:
          type: string
          description: Ad account name
        disabled:
          type: boolean
          description: Indicates whether the account is disabled.
        role:
          type: string
          description: Permission level
          enum:
            - OWNER
            - MASTER
            - STANDARD
            - READ_ONLY
            - PERFORMANCE_MANAGEMENT
        createdAt:
          type: string
          description: Creation time
          format: date-time
        updatedAt:
          type: string
          description: Last update time
          format: date-time
      description: OpenAPI ad account response
    PageOpenAdAccount:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        pageable:
          $ref: '#/components/schemas/PageableObject'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/SortObject'
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/OpenAdAccount'
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/SortObject'
        paged:
          type: boolean
        unpaged:
          type: boolean
        offset:
          type: integer
          format: int64
    SortObject:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean
    OpenMyManagerAccount:
      type: object
      properties:
        'no':
          type: integer
          format: int64
          description: Manager account ID
        name:
          type: string
          description: Manager account name
        disabled:
          type: boolean
          description: Indicates whether the account is disabled.
        createdAt:
          type: string
          format: date-time
          description: Creation time
        updatedAt:
          type: string
          format: date-time
          description: Last update time
        role:
          type: string
          description: Permission level
          enum:
            - OWNER
            - MASTER
            - STANDARD
            - READ_ONLY
            - PERFORMANCE_MANAGEMENT
    PageOpenMyManagerAccount:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        pageable:
          $ref: '#/components/schemas/PageableObject'
        first:
          type: boolean
        last:
          type: boolean
        sort:
          $ref: '#/components/schemas/SortObject'
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/OpenMyManagerAccount'
        empty:
          type: boolean
    OpenManagerAccount:
      type: object
      properties:
        childAdAccountNos:
          type: array
          description: Child ad account IDs
          items:
            type: integer
            format: int64
            description: Child ad account ID
        childManagerAccounts:
          type: array
          description: Child manager accounts
          items:
            $ref: '#/components/schemas/OpenManagerAccount'
        createdAt:
          type: string
          format: date-time
          description: Creation time
        disabled:
          type: boolean
          description: Indicates whether the account is disabled.
        name:
          type: string
          description: Manager account name
        'no':
          type: integer
          format: int64
          description: Manager account ID
        updatedAt:
          type: string
          format: date-time
          description: Last update time
      title: OpenManagerAccount
